# .github/workflows/deploy-supabase-functions.yml

name: Deploy Supabase Functions

on:
  push:
    branches:
      - main
    # Executa apenas se houver mudanças na pasta de funções
    paths:
      - 'supabase/functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/cli@v1
        with:
          version: latest

      - name: Deploy Supabase Functions
        # O comando 'supabase functions deploy' sem nomes específicos faz o deploy de todas as funções alteradas
        run: supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}